# Generated by Django 4.1 on 2022-08-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture_link',
            field=models.CharField(default='picturehere', max_length=200),
            preserve_default=False,
        ),
    ]
